services:
  nginx:
    image: nginx:latest
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./long
        target: /var/cache/nginx/long
    ports:
      - 7070:8080
      - 7071:7071